apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: bry-tam-policies-by-tag
  namespace: open-cluster-management-gitops
spec:
  generators:
  - list:
      elements:
      - environment: dev
        revision: appset-dev
      - environment: prod
        revision: appset-dev
  syncPolicy:
    preserveResourcesOnDeletion: true
  template:
    metadata:
      name: 'bry-policies-{{environment}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/brian-jarvis/bry-acm-policy-samples.git
        targetRevision: '{{revision}}'
        path: 'environments/{{environment}}'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: 'bry-tam-policies-{{environment}}'
      syncPolicy:
        automated:
          prune: true
          allowEmpty: true
          selfHeal: false
        syncOptions:
          - CreateNamespace=true
          - Validate=false
