apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: policy-manager
  namespace: open-cluster-management-gitops
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: open-cluster-management-gitops
  source:
    path: policy-manager/manage-by-tag
    repoURL: 'https://github.com/bry-tam/policy-release-managment.git'
    targetRevision: main
  project: default
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
  syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
    - ServerSideApply=true
    - Validate=false